@startuml
|Користувач|
start
: Оцінює виконавця за 10-бальною шкалою;

: Натискае кнопку "Оцінити";

|Система|
: Записує ім'я та оцінку в базу даних;
note right #ffaaaa
<b> Можливо
<b> EX.001.004
end note

: Перенаправляє на головну сторінку;

|Користувач|
- Має збережені ім'я та оцінку виконавця
stop;
@enduml