@startuml
|Користувач|
start
: Натискає на кнопку "Реєстрація";

|Система|
: Перенаправляє на сторінку реєстрації в системі;

|Користувач|
: Вводить:
 - e-mail
 - ім'я
 - пароль;

: Натискає кнопку "Зареєструватися";

|Система|
: Перевіряє введені дані;
note right #ffaaaa
<b> Можливо
<b> EX.001.001
<b> EX.001.002
end note

: Додає введені дані до бази даних;

|Користувач|
- Отримує новий обліковий запис
stop;
@enduml