@startuml
|Користувач|
start
: Натискае кнопку "Отримати рекомендації";

|Система|
: Формує список рекомендацій;
note right #ffaaaa
<b> Можливо
<b> EX.001.005
end note

: Перенаправляє на сторінку з рекомендаціями;

|Користувач|
- Отримує список рекомендованих виконавців
stop;
@enduml