@startuml
|Користувач|
start
: Натискає на кнопку "Головна сторінка";

|Система|
: Перенаправляє на головну сторінку;

|Користувач|
: Вводить ім'я виконавця;

: Натискає кнопку "Додати виконавця";

|Система|
: Зберігає введені дані;

: Перенаправляє на сторінку для оцінки введеного виконавця;

|Користувач|
- Отримує можливість оцінити виконавця
note right
<b> UC.04
end note
stop;
@enduml