@startuml
|Користувач|
start
: Натискає на кнопку "Вхід в систему";

|Система|
: Перенаправляє на сторінку входу в систему;

|Користувач|
: Вводить:
 - e-mail
 - пароль;

: Натискає кнопку "Увійти";

|Система|
: Перевіряє введені дані;
note right #ffaaaa
<b> Можливо
<b> EX.001.002
<b> EX.001.003
end note

|Користувач|
- Отримує доступ до свого облікового запису
stop;
@enduml